<?php
// ------------------------------------------------------------------------- //
// Copyright 2004, Daniel Coletti (dcoletti@xtech.com.ar)                    //
// This file is part of myconference XOOPS' module.                          //
//                                                                           //
// This program is free software; you can redistribute it and/or modify      //
// it under the terms of the GNU General Public License as published by      //
// the Free Software Foundation; either version 2 of the License, or         //
// (at your option) any later version.                                       //
//                                                                           //
// This program is distributed in the hope that it will be useful,           //
// but WITHOUT ANY WARRANTY; without even the implied warranty of            //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             //
// GNU General Public License for more details.                              //
//                                                                           //
// You should have received a copy of the GNU General Public License         //
// along with This program; if not, write to the Free Software               //
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA //
// ------------------------------------------------------------------------- //
$modversion['name']        = _MI_MYCONFERENCE_NAME;
$modversion['version']     = 1.01;
$modversion['description'] = _MI_MYCONFERENCE_DESC;
$modversion['author']      = 'Daniel Coletti ( http://www.xtech.com.ar/ ) XTech';
$modversion['official']    = 0;
$modversion['image']       = 'assets/images/logoModule.png';
$moduleDirName             = basename(__DIR__);
$modversion['dirname']     = $moduleDirName;
//$modversion['name'] = ucfirst(basename(__DIR__)); //no, because if somebody wants to clone, it will not work?

//$modversion['help'] = "myconference.html";
$modversion['help']        = 'page=help';
$modversion['license']     = 'GNU GPL 2.0 or later';
$modversion['license_url'] = 'www.gnu.org/licenses/gpl-2.0.html';

$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses/moduleadmin';
$modversion['sysicons16']     = 'Frameworks/moduleclasses/icons/16';
$modversion['sysicons32']     = 'Frameworks/moduleclasses/icons/32';
$modversion['modicons16']     = 'assets/images/icons/16';
$modversion['modicons32']     = 'assets/images/icons/32';
//about
$modversion['module_status']       = 'Beta 1';
$modversion['release_date']        = '2016/01/18';
$modversion['module_website_url']  = 'www.xoops.org';
$modversion['module_website_name'] = 'XOOPS';
$modversion['min_php']             = '5.5';
$modversion['min_xoops']           = '2.5.8';
$modversion['min_admin']           = '1.2';
$modversion['min_db']              = array(
    'mysql'  => '5.0.7',
    'mysqli' => '5.0.7'
);

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'myconference_bios';
$modversion['tables'][1] = 'myconference_speeches';
$modversion['tables'][2] = 'myconference_speech_types';
$modversion['tables'][3] = 'myconference_tracks';
$modversion['tables'][4] = 'myconference_main';
$modversion['tables'][5] = 'myconference_sections';

// Admin things
$modversion['hasAdmin']    = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex']  = 'admin/index.php';
$modversion['adminmenu']   = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = _MI_MYCONFERENCE_NEWSPEECH;
//$modversion['sub'][1]['url'] = "submit.php";
//$modversion['sub'][2]['name'] = _MI_MYCONFERENCE_NEWS_SMNAME2;
//$modversion['sub'][2]['url'] = "archive.php";

// Blocks
$modversion['blocks'][1]['file']        = 'myconference.php';
$modversion['blocks'][1]['name']        = _MI_MYCONFERENCE_BNAME;
$modversion['blocks'][1]['description'] = 'Shows tracks on a congress';
$modversion['blocks'][1]['show_func']   = 'b_myconference_show';
$modversion['blocks'][1]['options']     = '1';
$modversion['blocks'][1]['template']    = 'myconference_block.tpl';

// Templates
$modversion['templates'][1]['file']        = 'myconference_index.tpl';
$modversion['templates'][1]['description'] = 'Index';
$modversion['templates'][2]['file']        = 'myconference_speech.tpl';
$modversion['templates'][2]['description'] = 'Speech\'s info page';
$modversion['templates'][3]['file']        = 'myconference_track.tpl';
$modversion['templates'][3]['description'] = 'Track\'s info page';
$modversion['templates'][4]['file']        = 'myconference_bios.tpl';
$modversion['templates'][4]['description'] = 'Speaker\'s info page';

// ********************************************************************************************************************
// Preferences ********************************************************************************************************
// ********************************************************************************************************************
$modversion['config'][1]['name']        = 'max_imgheight';
$modversion['config'][1]['title']       = '_MI_MYCONFERENCE_MAX_HEIGHT';
$modversion['config'][1]['description'] = '_MI_MYCONFERENCE_MAX_HEIGHT_DESC';
$modversion['config'][1]['formtype']    = 'textbox';
$modversion['config'][1]['valuetype']   = 'int';
$modversion['config'][1]['default']     = '110';

$modversion['config'][2]['name']        = 'max_imgwidth';
$modversion['config'][2]['title']       = '_MI_MYCONFERENCE_MAX_WIDTH';
$modversion['config'][2]['description'] = '_MI_MYCONFERENCE_MAX_WIDTH_DESC';
$modversion['config'][2]['formtype']    = 'textbox';
$modversion['config'][2]['valuetype']   = 'int';
$modversion['config'][2]['default']     = '130';

$modversion['config'][3]['name']        = 'max_imgsize';
$modversion['config'][3]['title']       = '_MI_MYCONFERENCE_MAX_SIZE';
$modversion['config'][3]['description'] = '_MI_MYCONFERENCE_MAX_SIZE_DESC';
$modversion['config'][3]['formtype']    = 'textbox';
$modversion['config'][3]['valuetype']   = 'int';
$modversion['config'][3]['default']     = '10000';

$modversion['config'][4]['name']        = 'picsULdir';
$modversion['config'][4]['title']       = '_MI_MYCONFERENCE_FM_PICSULDIR';
$modversion['config'][4]['description'] = '_MI_MYCONFERENCE_FM_PICSULDIR_DESC';
$modversion['config'][4]['formtype']    = 'textbox';
$modversion['config'][4]['valuetype']   = 'text';
$modversion['config'][4]['default']     = 'modules/myconference/images/pictures';
