<?php
// ------------------------------------------------------------------------- //
// Copyright 2004, Daniel Coletti (dcoletti@xtech.com.ar)                    //
// This file is part of myconference XOOPS' module.                          //
//                                                                           //
// This program is free software; you can redistribute it and/or modify      //
// it under the terms of the GNU General Public License as published by      //
// the Free Software Foundation; either version 2 of the License, or         //
// (at your option) any later version.                                       //
//                                                                           //
// This program is distributed in the hope that it will be useful,           //
// but WITHOUT ANY WARRANTY; without even the implied warranty of            //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             //
// GNU General Public License for more details.                              //
//                                                                           //
// You should have received a copy of the GNU General Public License         //
// along with This program; if not, write to the Free Software               //
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA //
// ------------------------------------------------------------------------- //
$modversion['name'] = _MI_NAME;
$modversion['version'] = 0.9;
$modversion['description'] = _MI_DESC;
$modversion['author'] = "Daniel Coletti<br />( http://www.xtech.com.ar/ )<br />XTech";
$modversion['help'] = "myconference.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/myconference_slogo.png";
$modversion['dirname'] = "myconference";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "myconference_cvs";
$modversion['tables'][1] = "myconference_speeches";
$modversion['tables'][2] = "myconference_speech_types";
$modversion['tables'][3] = "myconference_tracks";
$modversion['tables'][4] = "myconference_main";
$modversion['tables'][5] = "myconference_sections";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = _MI_NEWSPEECH;
//$modversion['sub'][1]['url'] = "submit.php";
//$modversion['sub'][2]['name'] = _MI_NEWS_SMNAME2;
//$modversion['sub'][2]['url'] = "archive.php";

// Blocks
$modversion['blocks'][1]['file'] = "myconference.php";
$modversion['blocks'][1]['name'] = _MI_BNAME;
$modversion['blocks'][1]['description'] = "Shows tracks on a congress";
$modversion['blocks'][1]['show_func'] = "b_myconference_show";
$modversion['blocks'][1]['options'] = "1";
$modversion['blocks'][1]['template'] = 'myconference_block.html';

// Templates
$modversion['templates'][1]['file'] = 'myconference_index.html';
$modversion['templates'][1]['description'] = 'Index';
$modversion['templates'][2]['file'] = 'myconference_speech.html';
$modversion['templates'][2]['description'] = 'Speech\'s info page';
$modversion['templates'][3]['file'] = 'myconference_track.html';
$modversion['templates'][3]['description'] = 'Track\'s info page';
$modversion['templates'][4]['file'] = 'myconference_cv.html';
$modversion['templates'][4]['description'] = 'Speaker\'s info page';

?>
